services:
  # 1. El servicio de Base de datos
  mongodb:
    image: mongo:8.2.6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db

  inventory-db:
    image: mysql:8.4.8
    container_name: inventory-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=inventory-db
      - MYSQL_USER=inventory-user
      - MYSQL_PASSWORD=inventory-password
    volumes:
      - inventory_data:/var/lib/mysql

  order-db:
    image: postgres:18.0-alpine
    container_name: order-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=order-db
    volumes:
      - order_data:/var/lib/postgresql/data

  keycloak-db:
    image: postgres:18.0-alpine
    container_name: keycloak-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak-db
    volumes:
      - keycloak_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak-db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      # Credenciales del Super Admin (Para entrar a la consola administrativa)
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db

# 2. Nuestra Aplicación [Product Service]
#  products-service:
#    build: product-service
#    container_name: product-service
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATA_MONGODB_URI=mongodb://root:password@mongodb:27017/product-db?authSource=admin
#    depends_on:
#      - mongodb

volumes:
  mongodb_data:
  inventory_data:
  order_data:
  keycloak_data:
